### ISSUE TITLE
Can I install flake8 plugins?

### ISSUE THREAD

**Issue by Tacha-S** [reviewdog/action-flake8#32]
In this GitHub Action, only the default plugin for flake8 is installed.
Is it possible to install the flake8 plugin that the user needs by passing the plugin package name as inputs?

**Comment by rickstaa** [comment]
@Tacha-S, thanks for using our action. Since this is a composite action, any plugins you installed in the previous action step should be available. It might be that you need to activate the plugin since it is disabled by default (see [the flak8 documentation](https://flake8.pycqa.org/en/latest/user/using-plugins.html)). You can check whether the plugin is working by using the `--help` argument inside the `flake8_args` field of the action. Please let me know if you run into problems!

**Comment by Tacha-S** [comment]
Thanks for replying. I could install and enable plugins. But there was one more problem.
The errorfmt for flake8 seems to be [this one](https://github.com/reviewdog/errorformat/blob/master/fmts/python.go#L19), but the error type is set to something other than W or E depending on the plugin. For example, F{number} in [pyflake](https://flake8.pycqa.org/en/latest/user/error-codes.html), D{number} in [flake8-docstrings](http://www.pydocstyle.org/en/latest/error_codes.html#grouping), etc.
I don't know if this is the reason, but when flake8 detects these plugin errors, reviewdog does not report it.

**Comment by rickstaa** [comment]
@Tacha-S Thanks a lot for your response. It looks like Reviewdog is not aware of the reported errors since they are not defined in the used [errorformat](https://github.com/reviewdog/errorformat/blob/859f277de5cc66812bc3ecb7606e11b3fc62d527/fmts/python.go#L16-L24). The way to fix this is to modify the error format rule or add a second error format rule for the errors thrown by your plugin (see the [black errorformat](https://github.com/reviewdog/errorformat/blob/859f277de5cc66812bc3ecb7606e11b3fc62d527/fmts/python.go#L28-L36) as an example). Can you maybe create a pull request to the [errorformat](https://github.com/reviewdog/errorformat/blob/master/fmts/python.go) for this? A guide on how this is done can be found [here](https://github.com/reviewdog/errorformat/blob/master/fmts/README.md). A playground for testing your new error format is found [here](https://reviewdog.github.io/errorformat-playground/). Let me know if you need any help.

**Comment by Tacha-S** [comment]
I was mistaken, because the flake8 plugin warned me about a line in the GitHub pull request that was not included in the changes, and I thought it was not reported.

**Comment by rickstaa** [comment]
@Tacha-S No problem, thanks for investigating. Feel free to open another issue if you have any problems in the future.
